### ISSUE TITLE
lista prowadzacych

### ISSUE THREAD

**Issue by Kar0lLasek** [Mobilki5sem/PolitechnikaLodzka-application#3]
prowadzacy na FTIMS i ich ocena przez uzytkownikow. ranking.
po kliknieciu w prowadzacego mozna wyslac maila

**Comment by Kar0lLasek** [comment]
pobieranie ze strony informacji (wikamp) kopiowanie tekstu

**Comment by Bonniu** [comment]
na razie dziala zawsze dla pierwszego chlopa, np jest dwóch jacków rogowskich, na szczescie ten nasz jest jako pierwszy :D

**Comment by Kar0lLasek** [comment]
@Bonniu 

1. Otwieranie tylko pewnych informacji ze strony. Nie cała strona.
2. Poprawa graficznej oprawy. _Jednolite z menu?_

**Comment by Kar0lLasek** [comment]
POPRAWA DESIGN
